### ISSUE TITLE
lesson 14 broken

### ISSUE THREAD

**Issue by dawsonbotsford** [reactjs/react-router-tutorial#159]
Upon download, I execute `npm install` within `/react-router-tutorial/lessons/14-whats-next`. After this is installed, I execute `npm start` and the build begins. 

Webpack does it's work and tells me to visit `http://localhost:8080` to see the app, but I am greeted with the less-than-friends `Cannot GET /` response in my browser. There are no build errors, and webpack waits in it's post-build waiting state.

Am I doing something wrong?

<br>

---
[sist](https://github.com/dawsonbotsford/sist) output:

### OS
Darwin  
x64  

### shell  
`uname`: Darwin
`echo $SHELL`: /bin/zsh
`echo $TERM`: xterm-256color
`echo $TERM_PROGRAM`: iTerm.app

### node  
`npm -v`: 3.6.0
`node --version`: v5.7.1

Time created: Mon Apr 18 2016 18:16:23 GMT-0600 (MDT)

**Comment by Soweyln** [comment]
same for me

**Comment by dawsonbotsford** [comment]
@Soweyln thanks for chiming in! GitHub added support for reactions like " 👍 " months ago. Use that instead of "same" or "+1" comments. You can remove your previous comment and add a ":+1:" to my original post.

**Comment by Soweyln** [comment]
### shell
`uname`: Linux
`echo $SHELL`: /bin/zsh
`echo $TERM`: screen-256color
`echo $TERM_PROGRAM`:

### node
`npm -v`: 3.7.3
`node --version`: v5.9.1

Time created: Tue Apr 19 2016 13:58:35 GMT-0400 (EDT)

**Comment by Soweyln** [comment]
Actually I have some thoughts.
It does not work because webpack-dev-server is only serving the bundled js
but in the final code base, the page is rendered by server, and the static html
is not there anymore, so spin up another web server can solve the issue

**Comment by jamiehutber** [comment]
+1

**Comment by xiaopow** [comment]
Guys, npm start doesn't work because the static index.html is missing in /public for lesson 14. You just need to add it back it for it to work.

**Comment by dawsonbotsford** [comment]
If adding it back is required it should be in the source, right @xiaopow? Care to make a PR with your change?

**Comment by timdorr** [comment]
No, that is not correct. [The server has a built-in copy of the index.html file](https://github.com/reactjs/react-router-tutorial/blob/master/lessons/14-whats-next/server.js#L33-L43). 

Is `express.static` eating the index request?

**Comment by xiaopow** [comment]
Sorry, but it is true. Just need to add index.html back to /public. We are talking about `npm start` not `NODE_ENV=production npm start`

**Comment by timdorr** [comment]
No, it's not. The server is capable of rendering itself, so an index.html file is entirely redundant. Remove the `express.static` line and it will work.

The issue was that we weren't configuring that middleware to not do directory indexing. I've fixed that now.

**Comment by xiaopow** [comment]
Hey, I have swapped it with your fix `app.use(express.static(path.join(__dirname, 'public'), {index: false}))` but am still getting `Cannot GET /` for `npm start`.

`NODE_ENV=production npm start` works fine as usual.

**Comment by sameenzm** [comment]
hey, I have removed the `express.static` line, but it dosen't work too. Are you sure you have fixed that now ? @timdorr

**Comment by dawsonbotsford** [comment]
@sameenzm, what version are you running? Ensure you're on the newest and then if your problem persists, a "sist" output may help. See my first comment for the "sist" link.

**Comment by timdorr** [comment]
@sameenzm You should leave [that line](https://github.com/reactjs/react-router-tutorial/blob/master/lessons/14-whats-next/server.js#L14) in place. If you notice, we added the `{index: false}` option. That means it will serve up any file, *except* for any index file (e.g., `index.html` when you request `/`). This is so that [the server can do rendering](https://github.com/reactjs/react-router-tutorial/blob/master/lessons/14-whats-next/server.js#L17-L31) on those pages and send over pre-built HTML to the browser. If you serve up the index file, the browser will have to do the rendering and start from scratch.

**Comment by yura-master-web** [comment]
add index.html iv folder 'public' and npm start run
its work
